### ISSUE TITLE
OpenLibrary search produces too many results

### ISSUE THREAD

**Issue by mouse-reeve** [mouse-reeve/bookwyrm#226]

**Comment by ibrand** [comment]
Not sure if this is related, but I noticed that I'm getting "2 results" because one has a middle name initial on my localhost:
![Screen Shot 2020-10-22 at 12 34 37 PM](https://user-images.githubusercontent.com/3953117/96908998-01d53580-1463-11eb-893d-5622f4da0c72.png)
![Screen Shot 2020-10-22 at 12 34 44 PM](https://user-images.githubusercontent.com/3953117/96909000-026dcc00-1463-11eb-8b18-c1d8d4796f32.png)

Documenting here since it's definitely a symptom of "too many search results"

**Comment by mouse-reeve** [comment]
ah yeah, this is a separate issue - this isn't using search persay, it's suggesting multiple editions of the same book because there aren't enough books in the system. but it shouldn't display like this at all.
