### ISSUE TITLE
Display name is not set after joining an instance

### ISSUE THREAD

**Issue by Flameborn** [mouse-reeve/bookwyrm#698]
Currently, the user profile page relies on the display name, which is unset after joining an instance.

This results in the window title showing *none*.

I currently see two ways of fixing this:

1. Set the username as the display name by default, or
2. Ask for the display name during signup.

**Comment by mouse-reeve** [comment]
the `display_name` property will try `name` (the custom display name a user can set in their profile settings), then localname (`mouse`) then full username (`mouse@bookwyrm.social`). The title was showing None because I mistakenly set it to use `name` instead of `display_name`, so that's a quick fix.

**Comment by Flameborn** [comment]
Awesome, thank you!
