### ISSUE TITLE
Searches Related to Lists

### ISSUE THREAD

**Issue by nerdteacher** [mouse-reeve/bookwyrm#710]
I'm not entirely sure this is a bug? So I apologise if I chose the wrong option.

When creating lists and adding books, you can search for books. However, it doesn't pick the versions that are already on one  of your shelves. Using _The House on Mango Street_ by Sandra Cisneros as an example:

The version on my shelf is this one: https://bookwyrm.social/book/76286
![image](https://user-images.githubusercontent.com/77229429/110330941-b8a30e00-801e-11eb-8571-4b69ca3f5bb6.png)

However, it only gives me two options when I search for it on Lists. It's either this one:
![image](https://user-images.githubusercontent.com/77229429/110331038-d7090980-801e-11eb-9fb8-01eb55bf02c6.png)

Or this one:
![image](https://user-images.githubusercontent.com/77229429/110331082-e5572580-801e-11eb-897e-4106df93526e.png)

Would it be possible for the book pages to have an option to add them directly to lists rather than searching for them? (And if this is already in the works, sorry for cluttering things up!)

Also, sort of related to this and so I don't create more posts, I have a couple questions. 

1. Is it possible to have books on more than one shelf (i.e., Read + Custom Shelf)? (Perhaps any book that has reading data automatically sticks to the 'Read' shelf with options to organise/categorise it to custom shelves?)

2. Is it possible to reorganise the arrangement of the custom shelves? Like, if I make a new one, I can then move it next to something else in my list. (Such as if I want to make a 'Short Stories' shelf, but I want it to be located next the 'Plays' shelf. Or if I wanted to move 'Fiction' between 'Young Adult' and 'Graphic Novel'.)
![image](https://user-images.githubusercontent.com/77229429/110331562-91990c00-801f-11eb-9c06-a5e96f98c2fc.png)

**Comment by mouse-reeve** [comment]
Thank you! I'll take a look at improving search in the list view. 

Right now it's not possible to have books on multiple shelves, I'll make a new issue for that since the original conversation (#115) pre-dates some changes to the database. 

Ordering shelves wouldn't be a trivial change, but it's certainly _possible_ -- would you mind opening a separate issue for that?

**Comment by mouse-reeve** [comment]
I took a look at the problem with book search, and the issue is that the book sorting got misconfigured because of a bug, which was fixed a few months ago. I corrected the editions that show up in search for a bunch of books (house on mango street included). You can also add books to lists from the book page now. Let me know if you have other issues with lists! I'm stoked that you're making them
