### ISSUE TITLE
Support/Instructions for Running Bookwyrm Behind a Reverse-Proxy

### ISSUE THREAD

**Issue by bcj** [mouse-reeve/bookwyrm#717]
**Is your feature request related to a problem? Please describe.**

I am running my instance on the same machine as another webserver that is already bound to 80 & 443. This meant that the setup instructions would not work without modification because the nginx service would fail.

**Describe the solution you'd like**

In the setup instructions in the README, I would like a section describing the additional changes required if you are running another webserver on the same machine (assuming most people aren't doing this, I'd favour linking to that section from the main instructions instead of including it within the main setup instructions).

I would also like a commented out version of the alternate server configuration in `nginx/default.conf` and perhaps commented out versions of the docker changes in `docker-compose.yml`.

**Describe alternatives you've considered**

Right now, setting up an instance involves manually editing a bunch of files. If that is eventually going to be handled by some sort of configuration script/wizard, I'd love to see the option for specifying an alternate port for the nginx server and for turning off certbot/ssl (I have my system nginx server handling certificates since it already handles my other webserver's certificates).

Another option would be having the bookwyrm nginx server handle all my traffic and having it proxy/host anything else but that seems counter to running a dockerized nginx specifically for bookwyrm and I don't know how to accommodate that in setup instructions (I guess linking to nginx's proxy docs?).

**Comment by bcj** [comment]
I don't do a ton of web or docker stuff so it's quite possible I'm missing a more-obvious solution to the port issue.

If this is a use-case you want to accommodate, and my solution sounds good, I can write up a PR

**Comment by mouse-reeve** [comment]
hmmmmmmmm someone on mastodon was asking me about this! I'd be grateful for your writeup. Might be related to #658?

**Comment by bcj** [comment]
Cool, I'll do that write-up sometime this week then.

My issue definitely seems like a subset/smaller-scale version of theirs so maybe I will try to learn docker/compose a bit better after that and see if I could try tackling the more general issue

**Comment by bcj** [comment]
Also yeah, my original plan had been to remove the nginx service completely but I also couldn't work out what the good way to handle static/image stuff (the answer might involve binding the directory their in to a host directory but I didn't work out where I needed to be doing that because I don't know how the celery/flower stuff works)

**Comment by Flameborn** [comment]
The two issues are definitely related, as my original idea was to run Bookwyrm from Docker or possibly Podman via an image that has Gunicorn, Flower and Celery only, since the other requirements were met, i.e. I was running Caddy as a web server and reverse proxy, which also handles certificates via LetsEncrypt, a Postgres instance, Redis, etc, locally. Communication from a Docker image to the host machine did not seem to work for me, and I did not find a reliable way to do it cross-platform, but this might change in the future.

To disable the Nginx image, comment it out under *Services* in your *docker-compose.yml*. Proxy the *web* image's port 8000 via your local web server, this is already exposed if I am not mistaken. If not, you will need to expose it to your host machine.

You also need to serve the *static* and *images* directories from the mounted Docker volumes as */static* and */images*. For me, Docker put these directories in a *_data* directory inside each volume.

At this point, things should work as expected.

**Comment by mouse-reeve** [comment]
do yall feel that #720 sufficiently addressed this?

**Comment by bcj** [comment]
For my needs yeah
