### ISSUE TITLE
Preview Books Before Importing

### ISSUE THREAD

**Issue by bcj** [mouse-reeve/bookwyrm#718]
**Is your feature request related to a problem? Please describe.**

When importing a book that is not yet in Bookwyrm that has multiple OpenLibrary entries, there is no easy way to decide which version to choose without importing all of them or searching on OpenLibrary and comparing there.

E.g., searching Illiad gives `Illiad by Homer (2009)`, `The Illiad by Homer (1997)`, and `Homers Illiad by Unknown (1994)` (along with several results that aren't The Illiad)

**Describe the solution you'd like**

I would like the title of the entry to be a link to the OpenLibrary page (like how the already-imported books link to their Bookwyrm pages), and, ideally, a way to see at least some of the other metadata that would be imported without leaving the page.

**Describe alternatives you've considered**

If I could import by posting an OpenLibrary link (which I guess is related to #296), it could partially solve this since some books may not be distinguishable prior to import just from title/author/year.

Being able to directly add a book to Bookwyrm by supplying the information myself would also be useful but is significantly more work and adds ongoing moderation work.

**Comment by mouse-reeve** [comment]
You'll be able to add a book directly shortly (#692) but it's better for the data ecosystem if books are imported from outside datasets, because it builds on existing metadata and creates links between records. Agreed that it should show you more on the search page! There's quite a bit of data available at the search endpoint (https://openlibrary.org/search.json?q=illiad&mode=everything) so it's definitely possible to have clearer search records.

**Comment by bcj** [comment]
Nice. I will stick to adding things to OpenLibrary where it is also missing things since I agree it's better for everyone but having the option is definitely good

**Comment by mouse-reeve** [comment]
according to OL covers policy it should be chill to display cover previews 😄 https://openlibrary.org/dev/docs/api/covers
