### ISSUE TITLE
Lists

### ISSUE THREAD

**Issue by mouse-reeve** [mouse-reeve/bookwyrm#81]
So we have have, for example my beloved "trans novels by trans authors" list

Who owns a list and how are contributions moderated?

**Comment by mouse-reeve** [comment]
maybe this should just be shelves?

**Comment by 7596ff** [comment]
Apologies, I am only watching this project from afar, but if lists were just shelves, would a book in your collection show up like
- Shelves
  - Finished Reading
  - Trans novels by trans authors 

Instead of a separate lists section:
- Shelves
  - Finished Reading
- Lists
  - Trans novels by trans authors

And even if the backend storage is the same, a list would not be seen by a user the same as a shelf. If I see a list of books, I personally think "oh neat some books to add to my personal reading list" but if I see a shelf I think about lamborghinis

**Comment by 7596ff** [comment]
And for owners of a list, it could be owned by one person initially; that person could add collaborators (curators) to the list, the link to the list itself could (I don't know much about ActivityPub) be a post itself so it could have like counts
